version: '3.7'
services:
  example-sio-rtsp:
    build: .
    container_name: example-sio-output
    restart: always
    environment:
      - AMQP_HOST=192.168.99.37
      - AMQP_PORT=5672
    volumes:
      - ./src:/usr/src/app
      - ../lib:/usr/src/app/lib
#    networks:
#      core_sighthound:
#        aliases:
#          - example-sio-output

#networks:
#  core_sighthound:
#    external: true
