version: '3.7'
services:
  example-sio-rtsp:
    build: .
    container_name: example-sio-image-downloader
    restart: always
    ports:
      - "8554:8554"
    environment:
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - MCP_HOST=mcp
      - MCP_PORT=9097
      - MCP_USERNAME=root
      - MCP_PASSWORD=root
    volumes:
      - ./src:/usr/src/app
      - ../lib:/usr/src/app/lib
      - ./tmp:/tmp/sio
    networks:
      core_sighthound:
        aliases:
          - example-sio-image-downloader

networks:
  core_sighthound:
    external: true