version: "2"

services:
  mcp:
    image: ${MCP_DOCKER_IMAGE}:${MCP_DOCKER_TAG}
    restart: unless-stopped
    mem_limit: 1G
    mem_reservation: 512M
    volumes:
      - ${MEDIA_PATH}:/data/sighthound/media:rw
      - ${LOG_PATH}:/data/sighthound/logs/mcp:rw
      - ${DB_PATH}:/data/sighthound/db:rw
      - ./conf/mcp.yml:/etc/mcpd/default.json:ro
    ports:
      - "9097:9097"
    env_file:
      - .env
    networks:
      - core_sighthound

networks:
  core_sighthound:
    external: true

volumes:
  influxdb-persistent:
  influxdb-persistent-2:
