version: '3.7'
services:
  example-sio-rtsp:
    build: .
    container_name: event-webhooks
    restart: always
    environment:
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
    volumes:
      - ./src:/usr/src/app
      - ../lib:/usr/src/lib
      - ./cfg/config.json:/usr/src/cfg/config.json:ro
    command: ["/usr/bin/python3", "main.py", "--config_file", "/usr/src/cfg/config.json"]
    networks:
      core_sighthound:
        aliases:
          - event-webhooks

networks:
  core_sighthound:
    external: true